apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: vllm-test-june23
  janus-idp.io/tekton: vllm-test-june23
  backstage.io/kubernetes-id: vllm-test-june23
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: vllm-test-june23
resources:
  - application-dev.yaml