apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: vllm-test-june23
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vllm-test-june23
  name: vllm-test-june23
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
