apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: vllm-test-june23
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vllm-test-june23
  name: vllm-test-june23
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: vllm-test-june23
    weight: 100
  wildcardPolicy: None
