apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: vllm-test-june23
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vllm-test-june23
  name: vllm-test-june23
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: vllm-test-june23
